### PR TITLE
#185366586 Navigation Bar

### PR DESCRIPTION
**Pull request by irakevine**
## What does this PR do?

- To create  navigation menu that helps lead your user in the right direction. 

## Description of Task to be completed?

- Limit the number of menu options
- Concise names for your menu items
- Create categories and drop-down menus
- Boost conversions with a customized call-to-action button

## How should this be manually tested?

- Clone the repository using `git clone https://github.com/atlp-rwanda/e-comm-team-techsmith-fn`

- Checkout to the branch using `git checkout <ft-navbar-185366586>`

- Install node packages that the application depends on: `npm i`

- Create a `.env` file in the root directory and add all environment variables required to run the application. The required variables are listed in the `.env.example` file available in root directory of the application.

- Start the application development server: `npm start`

## What are the relevant pivotal tracker/Trello stories?
+ [#185366586](https://www.pivotaltracker.com/story/show/185366586)

## Screenshots (if appropriate)
Screenshot 2023-06-10 at 18 35 52

Screenshot 2023-06-10 at 18 38 19

Screenshot 2023-06-10 at 18 40 51

https://github.com/atlp-rwanda/e-comm-team-techsmith-fn/assets/64655121/87eaeb1f-8c5e-4f4c-9c35-2f0fda8100eb

### CODE REVIEW

**Review by irakozejules — APPROVED** [review]

**Review by jcharles921 — APPROVED** [review]
Great

**Review by jcharles921 — CHANGES_REQUESTED** [review]
Great work, can you add a navigation to the dashboard ?

**Review by jcharles921 — APPROVED** [review]

**Review by bergad37 — APPROVED** [review]
Great work!

**Review by bergad37 — APPROVED** [review]
Great work!

**Review by mken1205 — APPROVED** [review]
Great Work

**Review by Reennee — APPROVED** [review]

**Review by nishimweprince — APPROVED** [review]
@irakevine  this is perfect!! 🔥

**Review by niyontwali — APPROVED** [review]

**Pull request merged**
