### PR TITLE
Conditional Clear Cart

### PR DESCRIPTION
**Pull request by mken1205**
## What does this PR do?
Creating a condition for the "clear cart" button
## Description of Task to be completed?
Making a condition for the "clear cart" to disappear on an empty cart
## How should this be manually tested?

- Clone the repository using `git clone https://github.com/atlp-rwanda/e-comm-team-techsmith-fn`

- Checkout to the branch using `git checkout <branch-name>`

- Install node packages that the application depends on: `npm i`

- Create a `.env` file in the root directory and add all environment variables required to run the application. The required variables are listed in the `.env.example` file available in root directory of the application.

- Start the application development server: `npm start`

- Check out the components documentation: `npm run storybook`

## What are the relevant pivotal tracker/Trello stories?
[#185528216](https://www.pivotaltracker.com/story/show/185528216)
## Screenshots (if appropriate)

image

image

### CODE REVIEW

**Review by Gabriel-mdv — CHANGES_REQUESTED** [review]
Clicking the cart button in the navbar causing an issue. yes, the cart is being displayed, but the user navigates straight to the homepage while he is supposed to stay on the same page. can you please check what is happening at that button and revisit it?

**Review by Gabriel-mdv — APPROVED** [review]
Looks good now!

**Review by frankflej — APPROVED** [review]
The condition looks okay well done!

**Review by ReneNtabana — APPROVED** [review]

**Review by niyontwali — APPROVED** [review]

**Review by bergad37 — COMMENTED** [review]
Great work!!

**Pull request merged**
