### PR TITLE
#185486907 Fix unit tests for product features

### PR DESCRIPTION
**Pull request by nishimweprince**
## What does this PR do?

This PR fixes unit tests written for multiple product-related features.

### Writing unit tests for the following features
 - A buyer should be able to checkout
 - Users should be able to chat
 - A buyer should be able to make a payment using Stripe API
 - User/buyer should be able to add items to their cart
 - A user should be able to view products per category
 - A seller should be able to create/add items
 - Buyer should be able delete single item and delete All items in wishlist
 - A buyer should be able to add items to their wishlist

## How should this be manually tested?

- Clone the repository using `git clone https://github.com/atlp-rwanda/e-comm-team-techsmith-fn`

- Checkout to the branch using `git checkout bg-product-tests-185486907`

- Install node packages that the application depends on: `npm i`

- Create a `.env` file in the root directory and add all environment variables required to run the application. The required variables are listed in the `.env.example` file available in root directory of the application.

- Start the application development server: `npm start`

- Check out the components documentation: `npm run storybook`

## What are the relevant pivotal tracker/Trello stories?

- [#185486907](https://www.pivotaltracker.com/story/show/185486907)

### CODE REVIEW

**Review by irakevine — APPROVED** [review]
Great Work!

**Review by frankflej — APPROVED** [review]
Great keep it up!

**Review by ReneNtabana — APPROVED** [review]
Great work

**Review by jcharles921 — APPROVED** [review]
Great job 👍

**Review by Dyves1 — APPROVED** [review]

**Review by niyontwali — APPROVED** [review]

**Pull request merged**
