### PR TITLE
#185218912 Setup Github Actions to run tests

### PR DESCRIPTION
**Pull request by nishimweprince**
## What does this PR do?

This PR sets up Github Actions to run tests and generate coverage on every Pull Request (PR).

## Description of Task to be completed?

- Setting up Github Actions to run tests on every PR and generating coverage report.
- Adding the coverage badge in the README file of the repository

## How should this be manually tested?

- Clone the repository using `git clone https://github.com/atlp-rwanda/e-comm-team-techsmith-fn`

- Checkout to the branch using `git checkout ch-github-actions-185218912`

- Install node packages that the application depends on: `npm i`

- Create a `.env` file in the root directory and add all environment variables required to run the application. The required variables are listed in the `.env.example` file available in root directory of the application.

- Start the application development server: `npm run dev`

- Check the application's documentation on Storybook: `npm run storybook`

## Any background context you want to provide?

- The actions will mark tests as failed if they do not reach the set threshold, which is currently `80%`
- The coverage badge shared in the README is the existing one from Clode Climate as Github Actions does not generate code coverage out-of-the-box.

## What are the relevant pivotal tracker/Trello stories?

- [#185218912](https://www.pivotaltracker.com/story/show/185218912)

### CODE REVIEW

**Review by Dyves1 — APPROVED** [review]
perfect

**Review by jcharles921 — APPROVED** [review]
Great

**Review by cyubahiro367 — APPROVED** [review]
great job

**Review by ReneNtabana — APPROVED** [review]

**Review by frankflej — APPROVED** [review]
Nice work!

**Review by niyontwali — APPROVED** [review]

**Pull request merged**
