### PR TITLE
#185218907 Ch setup react router

### PR DESCRIPTION
**Pull request by jcharles921**
## What does this PR do?
This PR setup dummy routes to test the configuration of future endpoints we may use in our application.

## Description of Task to be completed?

This pull request introduces the integration of React Router into the project, providing efficient routing and navigation capabilities for the application. The changes made in this pull request aim to enhance the overall user experience by enabling seamless page transitions and dynamic URL routing.

## How should this be manually tested?

- Clone the repository using `git clone` [link](https://github.com/atlp-rwanda/e-comm-team-techsmith-fn)

- Checkout to the branch using `git checkout <branch-name>`

- Install node packages that the application depends on: `npm i`

- Create a `.env` file in the root directory and add all environment variables required to run the application. The required variables are listed in the `.env.example` file available in root directory of the application.

- Start the application development server: `npm run dev`
- Finally click on the local link `http://localhost:5173/` which will direct you to the react project in the browser

## What are the relevant pivotal tracker/Trello stories?

[#185218907](https://www.pivotaltracker.com/story/show/185218907)

### CODE REVIEW

**Review by irakozejules — APPROVED** [review]

**Review by irakozejules — APPROVED** [review]

**Review by bergad37 — APPROVED** [review]
Well done, now from this, more routes will be added as we do integration!

**Review by nishimweprince — APPROVED** [review]
Excellent setup!!

**Review by nishimweprince — CHANGES_REQUESTED** [review]
Excellent setup with the routes!!

I want to suggest that you update the commit message to use keywords specified in [Linking GitHub With PivotalTracker](https://github.com/atlp-rwanda/e-comm-team-techsmith-fn/tree/ch-setup-react-router-185218907#linking-github-with-pivotaltracker).

**Review by frankflej — APPROVED** [review]
Nice work but I would recommend to start using `exact` keyword in your routes to avoid errors in your routes for better practice.

**Review by irakevine — APPROVED** [review]
well done

**Review by nishimweprince — APPROVED** [review]

**Pull request merged**
