### PR TITLE
fixes(FilesCasing): applies pascalcase to all files

### PR DESCRIPTION
**Pull request by Gabriel-mdv**
## What does this PR do?
- Applies PascalCase to all files in components and containers
- fixes bug in redux
- ensures that sass is working well

## How should this be manually tested?

- Clone the repository using `git clone https://github.com/atlp-rwanda/e-comm-team-techsmith-fn`

- Checkout to the branch using `git checkout bugFix-structure_and_Case`

- Install node packages that the application depends on: `npm i`

- Create a `.env` file in the root directory and add all environment variables required to run the application. The required variables are listed in the `.env.example` file available in root directory of the application.

- Start the application development server: `npm start`

### CODE REVIEW

**Review by irakevine — APPROVED** [review]

**Review by frankflej — APPROVED** [review]
Nice work!

**Review by nishimweprince — APPROVED** [review]
Excellent work!!

**Review by jcharles921 — APPROVED** [review]
Great Job

**Review by Dyves1 — APPROVED** [review]
Well done ✅

**Pull request merged**
