### PR TITLE
#185218913 Ch-setup storybook for component development

### PR DESCRIPTION
**Pull request by jcharles921**
## What does this PR do?
This PR configure the [Storybook tool](https://storybook.js.org/) in our front-end application to improve the efficiency, reusability, and documentation of related components.
## Description of Task to be completed?

Configure the storybook tool (https://storybook.js.org/) to make the working on related components more efficient, easier to reuse and have better component documentation.

## How should this be manually tested?

- Clone the repository using `git clone` [link](https://github.com/atlp-rwanda/e-comm-team-techsmith-fn)

- Checkout to the branch using `git checkout <branch-name>`

- Install node packages that the application depends on: `npm i`

- Create a `.env` file in the root directory and add all environment variables required to run the application. The required variables are listed in the `.env.example` file available in root directory of the application.

- Start the application development server: `npm run storybook`

## Any background context you want to provide?

I highly encourage every team member to check this [tutorial](https://www.youtube.com/watch?v=FUKpWgRyPlU) on how to use storyBook.

## What are the relevant pivotal tracker/Trello stories?
[#185218913](https://www.pivotaltracker.com/story/show/185218913)

## Screenshots (if appropriate)
image

### CODE REVIEW

**Review by bergad37 — APPROVED** [review]
Great work done here!

**Review by ReneNtabana — APPROVED** [review]
Good job!

**Review by frankflej — APPROVED** [review]
Fantastic!!!

**Review by nishimweprince — APPROVED** [review]
Great work!!

**Review by Dyves1 — APPROVED** [review]
Okey 👍

**Review by irakevine — APPROVED** [review]
Great Work

**Review by niyontwali — APPROVED** [review]

**Pull request merged**
