### PR TITLE
#185467712 Bug fixes for the of pre-demo 22/06/2023

### PR DESCRIPTION
**Pull request by nishimweprince**
## What does this PR do?

This PR applies all feedbacks from the Pre-demo of June 22nd, 2023. It fixes identified bugs to ensure all features works as expected.

## Description of Task to be completed?

- Improves the authentication workflow by filtering users based on their roles.
- Improves data fetches, loading, and component re-rendering using useEffect.
- Improves route protection using outlets.
- Adds more meaningful feedback messages.

## How should this be manually tested?

- Clone the repository using `git clone https://github.com/atlp-rwanda/e-comm-team-techsmith-fn`

- Checkout to the branch using `git checkout bg-predemo-feedbacks-185467712`

- Install node packages that the application depends on: `npm i`

- Create a `.env` file in the root directory and add all environment variables required to run the application. The required variables are listed in the `.env.example` file available in root directory of the application.

- Start the application development server: `npm start`

- Check out the components documentation: `npm run storybook`

## What are the relevant pivotal tracker/Trello stories?

+ [#185467712](https://www.pivotaltracker.com/story/show/185467712)

### CODE REVIEW

**Review by jcharles921 — APPROVED** [review]
Greatly done

**Review by ReneNtabana — APPROVED** [review]

**Review by ReneNtabana — COMMENTED** [review]
Nice work

**Review by bergad37 — APPROVED** [review]

**Review by Gabriel-mdv — APPROVED** [review]
this is great.

**Review by Dyves1 — APPROVED** [review]

**Review by frankflej — APPROVED** [review]
Great work!

**Review by irakevine — APPROVED** [review]
Great Work!

**Review by niyontwali — APPROVED** [review]

**Pull request merged**
