### PR TITLE
#185218910 Code Climate test coverage on CI and PR template

### PR DESCRIPTION
**Pull request by nishimweprince**
## What does this PR do?

This PR sets up up automatic tests coverage reports using CodeClimate Quality and Circle CI with Continuous Integrations. It also adds a PR template for standardization.

## Description of Task to be completed?

+ Running codeclimate test coverage after passing the tests on Circle CI
+ Adding a maintainability badge after successful test run with CI
+ Adding Pull Request template adhering to ATLP's Engineering Playbook

## How should this be manually tested?

- Clone the repository using `git clone https://github.com/atlp-rwanda/e-comm-team-techsmith-fn.git` 

- Checkout to the branch using `git checkout ch-testcoverage-185218910`

- Install node packages that the application depends on: `npm i`

- Create a `.env` file in the root directory and add all environment variables required to run the application. The required variables are listed in the `.env.example` file available in root directory of the application.

- Start the application development server: `npm start`

## Any background context you want to provide?

The task creates a structure which may differ from React's for testing purposes.

## What are the relevant pivotal tracker/Trello stories?

+ [#185218910](https://www.pivotaltracker.com/story/show/185218910)

### CODE REVIEW

**Review by jcharles921 — CHANGES_REQUESTED** [review]
can you put the coverage folder in gitignore ?

**Comment by nishimweprince** [comment]
> can you put the coverage folder in gitignore ?

Yes I have updated my .gitignore you may check. Thanks!

**Review by bergad37 — APPROVED** [review]

**Review by jcharles921 — APPROVED** [review]
great work

**Review by frankflej — APPROVED** [review]
Nice work!

**Review by niyontwali — APPROVED** [review]

**Review by irakevine — APPROVED** [review]

**Pull request merged**
